apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress  
  namespace: calculadora
spec:
  rules:
  - host: "calcu.modelodevops.sociuschile.cl"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calculadora
            port:
              number: 80
